var nome = "Ariel Alves";
var idade = 22;
var idade2 = 10;
var frase = "japão é o melhor time do mundo";
//alert(nome+" tem "+idade);
console.log(nome);
console.log(idade+idade2);
console.log(frase.replace("japão", "Brasil"));
console.log(frase.toUpperCase());
alert(frase.replace("japão", "Brasil"));